export const WEAPONS={
 fireball:{name:'Bola de Fogo',icon:'🔥',type:'projectile',element:'fire',max:5,damage:24,cooldown:1.05,speed:370,area:48,desc:'Procura um inimigo e explode.'},
 arrow:{name:'Arco',icon:'🏹',type:'projectile',element:'physical',max:5,damage:18,cooldown:.62,speed:560,area:10,pierce:1,desc:'Flechas rápidas e precisas.'},
 skeleton:{name:'Esqueleto Guerreiro',icon:'💀',type:'summon',element:'shadow',max:5,damage:16,cooldown:2.2,desc:'Invoca esqueletos autônomos.'},
 sword:{name:'Espada',icon:'🗡️',type:'melee',element:'physical',max:5,damage:32,cooldown:.8,area:82,desc:'Golpe circular próximo.'},
 lightning:{name:'Raio',icon:'⚡',type:'lightning',element:'electric',max:5,damage:28,cooldown:1.25,desc:'Atinge inimigos instantaneamente.'},
 ice:{name:'Fragmentos de Gelo',icon:'❄️',type:'ice',element:'ice',max:5,damage:18,cooldown:1.1,speed:330,area:14,desc:'Projéteis que congelam.'},
 axe:{name:'Machado',icon:'🪓',type:'orbitShot',element:'physical',max:5,damage:31,cooldown:1.4,speed:250,area:18,desc:'Machado pesado atravessa inimigos.'},
 aura:{name:'Aura Arcana',icon:'🟣',type:'aura',element:'shadow',max:5,damage:9,cooldown:.35,area:96,desc:'Dano contínuo ao redor.'},
 meteor:{name:'Meteoro',icon:'☄️',type:'meteor',element:'fire',max:5,damage:62,cooldown:2.8,area:75,desc:'Meteoros caem perto dos inimigos.'},
 boomerang:{name:'Bumerangue',icon:'➰',type:'orbitShot',element:'physical',max:5,damage:24,cooldown:1.15,speed:280,area:16,desc:'Projétil perfurante curvo.'},
 poison:{name:'Flecha Venenosa',icon:'☠️',type:'projectile',element:'poison',max:5,damage:15,cooldown:.86,speed:420,area:11,desc:'Aplica veneno acumulável.'},
 deathAura:{name:'Aura da Morte',icon:'🕯️',type:'aura',element:'shadow',max:5,damage:11,cooldown:.42,area:112,desc:'Enfraquece tudo ao redor.'},
 shield:{name:'Escudo Giratório',icon:'🛡️',type:'orbit',element:'physical',max:5,damage:20,cooldown:.25,area:28,desc:'Escudos orbitam o herói.'},
 holySpear:{name:'Lança Sagrada',icon:'🔱',type:'projectile',element:'holy',max:5,damage:36,cooldown:1.3,speed:460,area:13,desc:'Lança perfurante de longo alcance.'},
 storm:{name:'Tempestade',icon:'🌩️',type:'lightning',element:'electric',max:5,damage:22,cooldown:.92,desc:'Raios saltam entre alvos.'},
 infernalSun:{name:'Sol Infernal',icon:'☀️',type:'projectile',element:'fire',max:1,damage:110,cooldown:1.1,speed:270,area:110,pierce:20,evolved:true,desc:'Esfera flamejante devastadora.'},
 frozenStorm:{name:'Tempestade Congelante',icon:'🌨️',type:'aura',element:'ice',max:1,damage:30,cooldown:.26,area:165,evolved:true,desc:'Congela e fulmina a área.'},
 cursedLegion:{name:'Legião Amaldiçoada',icon:'👑',type:'summon',element:'shadow',max:1,damage:42,cooldown:1.1,evolved:true,desc:'Invoca uma legião fortalecida.'},
 divineEye:{name:'Olho Divino',icon:'🎯',type:'projectile',element:'holy',max:1,damage:52,cooldown:.32,speed:680,area:12,pierce:4,evolved:true,desc:'Disparos críticos em alta velocidade.'}
};
