import{GAME_CONFIG,ENEMIES,PASSIVES,EVOLUTIONS}from'./config.js';
import{Player}from'./entities/player.js';import{Enemy}from'./entities/enemy.js';import{Camera}from'./camera.js';import{SpatialGrid}from'./systems/spatialGrid.js';import{WeaponSystem,WEAPONS}from'./weapons/weapons.js';
export class Game{
 constructor(canvas,input,ui,save){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.input=input;this.ui=ui;this.save=save;this.camera=new Camera();this.grid=new SpatialGrid(GAME_CONFIG.gridSize);this.running=false;this.paused=false;this.last=0;this.resize();addEventListener('resize',()=>this.resize());}
 start(charId,mapId){this.charId=charId;this.mapId=mapId;this.player=new Player(this.ui.characters[charId],this.save.data.meta);this.player.weapons[this.ui.characters[charId].startWeapon]=1;this.time=0;this.pendingLevels=0;this.enemies=[];this.projectiles=[];this.enemyProjectiles=[];this.pickups=[];this.particles=[];this.numbers=[];this.meteors=[];this.hazards=[];this.summons=[];this.orbitVisuals=[];this.weaponDamage={};this.spawnAcc=0;this.miniboss1=false;this.miniboss2=false;this.finalSpawned=false;this.victory=false;this.ended=false;this.shake=0;this.weaponSystem=new WeaponSystem(this);this.running=true;this.paused=false;this.last=performance.now();this.ui.showGame();requestAnimationFrame(t=>this.loop(t));}
 resize(){this.canvas.width=Math.floor(innerWidth*devicePixelRatio);this.canvas.height=Math.floor(innerHeight*devicePixelRatio);this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);this.camera.resize(innerWidth,innerHeight)}
 loop(t){if(!this.running)return;const dt=Math.min(.033,(t-this.last)/1000||0);this.last=t;if(this.input.consume('Escape'))this.togglePause();if(!this.paused&&!this.ended)this.update(dt);this.render();this.input.endFrame();requestAnimationFrame(n=>this.loop(n));}
 update(dt){this.time+=dt;this.player.update(this.input,dt,{w:GAME_CONFIG.worldWidth,h:GAME_CONFIG.worldHeight});this.camera.update(this.player,dt);this.spawnAcc+=dt;const perf=this.save.data.settings.performance,max=perf?GAME_CONFIG.performanceMaxEnemies:GAME_CONFIG.maxEnemies;if(this.spawnAcc>.22&&this.enemies.length<max){this.spawnAcc=0;const count=Math.min(1+Math.floor(this.time/180),5);for(let i=0;i<count;i++)this.spawnEnemy(this.chooseEnemy())}if(this.time>600&&!this.miniboss1){this.spawnBoss('ogreBoss');this.miniboss1=true}if(this.time>900&&!this.miniboss2){this.spawnBoss('lichBoss');this.miniboss2=true}if(this.time>GAME_CONFIG.finalBossTime&&!this.finalSpawned){this.spawnBoss('finalBoss');this.finalSpawned=true}
 this.grid.clear();for(const e of this.enemies)if(!e.dead)this.grid.insert(e);for(const e of this.enemies)if(!e.dead)e.update(this,dt);this.weaponSystem.update(dt);this.updateProjectiles(dt);this.updateEnemyProjectiles(dt);this.updatePickups(dt);this.updateMeteors(dt);this.updateHazards(dt);this.updateSummons(dt);this.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});this.particles=this.particles.filter(p=>p.life>0).slice(-350);this.numbers.forEach(n=>{n.life-=dt;n.y-=28*dt});this.numbers=this.numbers.filter(n=>n.life>0).slice(-160);this.enemies=this.enemies.filter(e=>!e.dead&&Math.abs(e.x-this.player.x)<1800&&Math.abs(e.y-this.player.y)<1800);this.shake=Math.max(0,this.shake-dt);this.checkLevel();this.checkEvolution();if(!this.player.alive)this.end(false);this.ui.updateHUD(this);}
 chooseEnemy(){const m=this.time/60,r=Math.random();if(m<2)return r<.7?'slime':'bat';if(m<5)return r<.4?'slime':r<.7?'goblin':'skeleton';if(m<10)return r<.25?'goblin':r<.5?'skeleton':r<.75?'bat':'orc';if(m<15)return r<.22?'orc':r<.45?'darkMage':r<.52?'elite':'skeleton';return r<.18?'elite':r<.4?'orc':r<.62?'darkMage':r<.8?'goblin':'skeleton'}
 spawnEnemy(type){const c=this.camera,side=Math.floor(Math.random()*4),margin=GAME_CONFIG.spawnMargin;let x,y;if(side===0){x=c.x-margin;y=c.y+Math.random()*c.h}else if(side===1){x=c.x+c.w+margin;y=c.y+Math.random()*c.h}else if(side===2){x=c.x+Math.random()*c.w;y=c.y-margin}else{x=c.x+Math.random()*c.w;y=c.y+c.h+margin}x=Math.max(20,Math.min(GAME_CONFIG.worldWidth-20,x));y=Math.max(20,Math.min(GAME_CONFIG.worldHeight-20,y));const scale=1+Math.max(0,this.time-120)/700;this.enemies.push(new Enemy(type,ENEMIES[type],x,y,scale))}
 spawnBoss(type){const a=Math.random()*Math.PI*2,d=Math.max(innerWidth,innerHeight)*.65;const e=new Enemy(type,ENEMIES[type],this.player.x+Math.cos(a)*d,this.player.y+Math.sin(a)*d,1+this.time/1500);this.enemies.push(e);this.ui.setBoss(e)}
 nearestEnemy(x,y,r){let best=null,bd=r*r;for(const e of this.enemies){if(e.dead)continue;const d=(e.x-x)**2+(e.y-y)**2;if(d<bd){bd=d;best=e}}return best}randomEnemy(){const a=this.enemies.filter(e=>!e.dead);return a.length?a[(Math.random()*a.length)|0]:null}closestEnemies(x,y,r,n){return this.enemies.filter(e=>!e.dead&&Math.hypot(e.x-x,e.y-y)<=r).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y)).slice(0,n)}
 spawnProjectile(o){this.projectiles.push({...o,life:3,dead:false})}spawnEnemyProjectile(x,y,nx,ny,dmg){this.enemyProjectiles.push({x,y,vx:nx*240,vy:ny*240,r:7,damage:dmg,life:5})}radialEnemyShots(e,n,dmg){for(let i=0;i<n;i++){const a=i*Math.PI*2/n;this.spawnEnemyProjectile(e.x,e.y,Math.cos(a),Math.sin(a),dmg)}}spawnHazardNearPlayer(dmg){this.hazards.push({x:this.player.x+(Math.random()-.5)*340,y:this.player.y+(Math.random()-.5)*340,r:70,t:1.2,damage:dmg,hit:false})}
 updateProjectiles(dt){for(const p of this.projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;const near=this.grid.query(p.x,p.y,p.r+35);for(const e of near){if(e.dead)continue;if(Math.hypot(e.x-p.x,e.y-p.y)<e.size+p.r){this.damageEnemy(e,p.damage,true,p.element,true);if(p.freeze)e.status.freeze=Math.max(e.status.freeze,1.3);if(p.poison){e.status.poison=3;e.status.poisonDps=Math.min(30,e.status.poisonDps+3)}if(p.explode)this.areaHit(p.x,p.y,p.explode,p.damage*.55,p.element,0);p.pierce--;if(p.pierce<0){p.dead=true;break}}}}this.projectiles=this.projectiles.filter(p=>p.life>0&&!p.dead)}
 updateEnemyProjectiles(dt){for(const p of this.enemyProjectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(Math.hypot(p.x-this.player.x,p.y-this.player.y)<p.r+this.player.r){this.player.takeDamage(p.damage);p.life=0}}this.enemyProjectiles=this.enemyProjectiles.filter(p=>p.life>0)}
 updatePickups(dt){for(const p of this.pickups){p.life-=dt;const d=Math.hypot(this.player.x-p.x,this.player.y-p.y);if(d<this.player.pickup){const s=Math.min(1,dt*8);p.x+=(this.player.x-p.x)*s;p.y+=(this.player.y-p.y)*s}if(d<24){if(p.type==='xp')this.pendingLevels+=this.player.gainXp(p.value);if(p.type==='coin')this.player.coins+=p.value;if(p.type==='heal')this.player.hp=Math.min(this.player.maxHp,this.player.hp+25);if(p.type==='magnet')for(const q of this.pickups)if(q.type==='xp'){q.x=this.player.x+(Math.random()-.5)*25;q.y=this.player.y+(Math.random()-.5)*25}if(p.type==='chest')this.openChest();p.life=0}}this.pickups=this.pickups.filter(p=>p.life>0)}
 updateMeteors(dt){for(const m of this.meteors){m.t-=dt;if(m.t<=0&&!m.hit){m.hit=true;this.areaHit(m.x,m.y,m.r,m.damage,'fire',0);this.burst(m.x,m.y,'#ff784e',24)} }this.meteors=this.meteors.filter(m=>m.t>-.25)}createMeteor(x,y,dmg,r){this.meteors.push({x,y,damage:dmg,r,t:.65,hit:false})}
 updateHazards(dt){for(const h of this.hazards){h.t-=dt;if(h.t<=0&&!h.hit){h.hit=true;if(Math.hypot(h.x-this.player.x,h.y-this.player.y)<h.r+this.player.r)this.player.takeDamage(h.damage)}}this.hazards=this.hazards.filter(h=>h.t>-.25)}
 ensureSummons(id,count,damage){while(this.summons.filter(s=>s.id===id).length<count){const a=Math.random()*Math.PI*2;this.summons.push({id,x:this.player.x+Math.cos(a)*45,y:this.player.y+Math.sin(a)*45,damage,cd:Math.random()*.5})}}
 updateSummons(dt){for(const s of this.summons){s.cd-=dt;const t=this.nearestEnemy(s.x,s.y,520);if(t){const dx=t.x-s.x,dy=t.y-s.y,d=Math.hypot(dx,dy)||1;s.x+=dx/d*145*dt;s.y+=dy/d*145*dt;if(d<28+t.size&&s.cd<=0){this.damageEnemy(t,s.damage,true,'shadow',true);s.cd=.7}}else{s.x+=(this.player.x-s.x)*dt;s.y+=(this.player.y-s.y)*dt}}}
 areaHit(x,y,r,damage,element,freeze=0,continuous=false){for(const e of this.grid.query(x,y,r+40)){if(e.dead)continue;if(Math.hypot(e.x-x,e.y-y)<r+e.size){this.damageEnemy(e,damage,!continuous,element,!continuous);if(freeze)e.status.freeze=Math.max(e.status.freeze,freeze);if(element==='fire'){e.status.burn=2.5;e.status.burnDps=Math.max(e.status.burnDps,damage*.08)}}}}
 damageEnemy(e,damage,canCrit=true,element='physical',number=true){if(e.dead)return;let crit=false;if(canCrit&&Math.random()<this.player.crit){damage*=this.player.critDamage;crit=true}e.hp-=damage;e.hitFlash=.08;this.player.damageDone+=damage;this.weaponDamage[element]=(this.weaponDamage[element]||0)+damage;if(number&&this.save.data.settings.damageNumbers)this.numbers.push({x:e.x,y:e.y-10,text:Math.round(damage)+(crit?'!':''),crit,life:.65});if(e.hp<=0)this.killEnemy(e)}
 killEnemy(e){if(e.dead)return;e.dead=true;this.player.kills++;this.pickups.push({type:'xp',x:e.x,y:e.y,value:e.xp,life:GAME_CONFIG.pickupLife});if(Math.random()<e.coin)this.pickups.push({type:'coin',x:e.x+8,y:e.y,value:e.boss?e.coin:1,life:60});if(Math.random()<.012)this.pickups.push({type:'heal',x:e.x,y:e.y-8,value:1,life:30});if(Math.random()<.004)this.pickups.push({type:'magnet',x:e.x,y:e.y+8,value:1,life:30});if(e.boss){this.pickups.push({type:'chest',x:e.x,y:e.y,value:1,life:60});if(e.type!=='finalBoss'){this.save.data.records.miniboss=true}if(e.type==='finalBoss'){this.victory=true;this.end(true)}}this.burst(e.x,e.y,e.color,8)}
 burst(x,y,color,n){if(this.save.data.settings.particles===0)return;const count=Math.min(n*this.save.data.settings.particles,40);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*120;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.45,color})}}
 checkLevel(){if(this.pendingLevels>0&&!this.paused){this.pendingLevels--;this.paused=true;this.ui.showLevelUp(this.getChoices(),c=>{this.applyChoice(c);this.paused=false})}}
 getChoices(){const options=[];for(const[id,w]of Object.entries(WEAPONS)){const lv=this.player.weapons[id]||0;if(w.evolved)continue;if(lv>0&&lv<w.max)options.push({kind:'weapon',id,name:w.name,icon:w.icon,desc:`Nv.${lv+1} • ${w.desc}`});else if(lv===0&&Object.keys(this.player.weapons).length<6)options.push({kind:'weapon',id,name:w.name,icon:w.icon,desc:`NOVA ARMA • ${w.desc}`})}for(const[id,p]of Object.entries(PASSIVES)){const lv=this.player.passives[id]||0;if(lv<p.max&&(lv>0||Object.keys(this.player.passives).length<6))options.push({kind:'passive',id,name:p.name,icon:p.icon,desc:p.desc})}for(let i=options.length-1;i>0;i--){const j=(Math.random()*(i+1))|0;[options[i],options[j]]=[options[j],options[i]]}return options.slice(0,3).map(o=>({...o,rarity:this.rollRarity()}))}
 rollRarity(){const r=Math.random();return r<.03?'legendary':r<.1?'epic':r<.25?'rare':r<.5?'uncommon':'common'}
 applyChoice(c){const bonus={common:1,uncommon:1.05,rare:1.1,epic:1.16,legendary:1.25}[c.rarity]||1;if(c.kind==='weapon'){this.player.weapons[c.id]=(this.player.weapons[c.id]||0)+1;if(bonus>1)this.player.damage*=1+(bonus-1)*.08}else{this.player.passives[c.id]=(this.player.passives[c.id]||0)+1;PASSIVES[c.id].apply(this.player);if(bonus>1)this.player.maxHp+=Math.round((bonus-1)*20)}this.ui.refreshWeaponBar(this.player)}
 checkEvolution(){for(const evo of EVOLUTIONS){if(this.player.weapons[evo.weapon])continue;let ok=true;for(const r of evo.requires){if(WEAPONS[r])ok&=(this.player.weapons[r]||0)>=WEAPONS[r].max;else ok&=(this.player.passives[r]||0)>0}if(ok){this.player.weapons[evo.weapon]=1;const replace=evo.requires.find(r=>WEAPONS[r]);if(replace)delete this.player.weapons[replace];this.save.discover(evo.id);this.ui.flashMessage(`EVOLUÇÃO: ${evo.name}`);this.ui.refreshWeaponBar(this.player)}}}
 openChest(){if(this.paused)return;this.paused=true;const c=this.getChoices()[0];if(c)this.applyChoice(c);this.ui.showChest(c,()=>this.paused=false)}togglePause(){if(this.ended)return;this.paused=!this.paused;this.ui.showPause(this.paused)}restart(){this.start(this.charId,this.mapId)}quit(){this.running=false;this.paused=false;this.ui.showMain()}
 end(victory){if(this.ended)return;this.ended=true;this.paused=true;const run={time:this.time,level:this.player.level,kills:this.player.kills,coins:this.player.coins,miniboss:this.miniboss1,victory};this.save.finishRun(run);this.ui.showEnd(this,victory)}
 render(){const c=this.ctx;c.save();c.clearRect(0,0,innerWidth,innerHeight);let sx=0,sy=0;if(this.shake>0&&this.save.data.settings.shake){sx=(Math.random()-.5)*8;sy=(Math.random()-.5)*8}c.translate(sx,sy);this.drawWorld(c);for(const p of this.pickups)this.drawPickup(c,p);for(const h of this.hazards)this.drawHazard(c,h);for(const m of this.meteors)this.drawMeteor(c,m);for(const e of this.enemies)this.drawEnemy(c,e);for(const p of this.projectiles)this.drawProjectile(c,p);for(const p of this.enemyProjectiles)this.drawEnemyProjectile(c,p);for(const s of this.summons)this.drawSummon(c,s);for(const o of this.orbitVisuals)this.drawCircleWorld(c,o.x,o.y,o.r,'#d4d8cc');this.orbitVisuals=[];for(const p of this.particles)this.drawCircleWorld(c,p.x,p.y,3,p.color);this.drawPlayer(c);for(const n of this.numbers)this.drawNumber(c,n);c.restore()}
 drawWorld(c){const map=this.ui.maps[this.mapId];c.fillStyle=map.ground;c.fillRect(0,0,innerWidth,innerHeight);const step=140,startX=Math.floor(this.camera.x/step)*step,startY=Math.floor(this.camera.y/step)*step;c.fillStyle=map.accent;for(let x=startX;x<this.camera.x+innerWidth+step;x+=step)for(let y=startY;y<this.camera.y+innerHeight+step;y+=step){const sx=x-this.camera.x,sy=y-this.camera.y;const seed=(x*13+y*7)%97;c.globalAlpha=.22;c.beginPath();c.arc(sx+(seed%30),sy+(seed%23),3+(seed%8),0,Math.PI*2);c.fill()}c.globalAlpha=1}
 drawCircleWorld(c,x,y,r,color){const s=this.camera.worldToScreen(x,y);if(!this.camera.visible(x,y,r))return;c.fillStyle=color;c.beginPath();c.arc(s.x,s.y,r,0,Math.PI*2);c.fill()}
 drawPlayer(c){const s=this.camera.worldToScreen(this.player.x,this.player.y);c.save();c.translate(s.x,s.y);c.fillStyle=this.player.iframes>0?'#ffffff':'#67e0b6';c.beginPath();c.arc(0,0,this.player.r,0,Math.PI*2);c.fill();c.strokeStyle='#d9fff1';c.lineWidth=3;c.stroke();c.fillStyle='#08221b';c.fillRect(-5,-4,3,3);c.fillRect(4,-4,3,3);c.restore()}
 drawEnemy(c,e){if(!this.camera.visible(e.x,e.y,e.size+5))return;const s=this.camera.worldToScreen(e.x,e.y);c.fillStyle=e.hitFlash>0?'#fff':e.color;c.beginPath();c.arc(s.x,s.y,e.size,0,Math.PI*2);c.fill();if(e.boss){c.strokeStyle='#f7d67c';c.lineWidth=3;c.stroke();const w=e.size*2;c.fillStyle='#1b0d12';c.fillRect(s.x-e.size,s.y-e.size-12,w,5);c.fillStyle='#e44f75';c.fillRect(s.x-e.size,s.y-e.size-12,w*Math.max(0,e.hp/e.maxHp),5)}}
 drawProjectile(c,p){this.drawCircleWorld(c,p.x,p.y,Math.min(p.r,18),GAME_CONFIG.colors[p.element]||'#fff')}drawEnemyProjectile(c,p){this.drawCircleWorld(c,p.x,p.y,p.r,'#e95d93')}
 drawPickup(c,p){const col=p.type==='xp'?'#56d7ff':p.type==='coin'?'#ffd45c':p.type==='heal'?'#75ef91':p.type==='magnet'?'#d773ff':'#d6ae52';this.drawCircleWorld(c,p.x,p.y,p.type==='chest'?11:6,col)}drawSummon(c,s){this.drawCircleWorld(c,s.x,s.y,10,'#c9c2a2')}
 drawMeteor(c,m){const s=this.camera.worldToScreen(m.x,m.y);c.strokeStyle='#ff8a4a';c.lineWidth=3;c.beginPath();c.arc(s.x,s.y,m.r*(1-m.t*.3),0,Math.PI*2);c.stroke()}drawHazard(c,h){const s=this.camera.worldToScreen(h.x,h.y);c.fillStyle=h.hit?'#8f274155':'#bf335c33';c.beginPath();c.arc(s.x,s.y,h.r,0,Math.PI*2);c.fill();c.strokeStyle='#d84b6e';c.stroke()}
 drawNumber(c,n){const s=this.camera.worldToScreen(n.x,n.y);c.globalAlpha=Math.max(0,n.life/.65);c.font=n.crit?'bold 18px system-ui':'bold 14px system-ui';c.fillStyle=n.crit?'#ffe26f':'#fff';c.textAlign='center';c.fillText(n.text,s.x,s.y);c.globalAlpha=1}
}
