import{CHARACTERS,MAPS,META_UPGRADES,EVOLUTIONS,PASSIVES}from'../config.js';import{WEAPONS}from'../weapons/weaponData.js';
export class UI{
 constructor(save){this.save=save;this.characters=CHARACTERS;this.maps=MAPS;this.selectedCharacter=null;this.selectedMap=null;this.game=null;this.bindBase();this.renderCharacters();this.renderMaps();this.renderMeta();this.renderGrimoire();this.renderSettings()}
 setGame(g){this.game=g}
 showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active')}
 showMain(){this.showScreen('mainMenu');document.getElementById('hud').classList.add('hidden');document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));this.renderCharacters();this.renderMeta();this.renderGrimoire()}
 showGame(){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('hud').classList.remove('hidden');this.refreshWeaponBar(this.game.player)}
 bindBase(){document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='play'||a==='characters'){this.renderCharacters();this.showScreen('characterScreen')}else if(a==='meta'){this.renderMeta();this.showScreen('metaScreen')}else if(a==='grimoire'){this.renderGrimoire();this.showScreen('grimoireScreen')}else if(a==='settings'){this.renderSettings();this.showScreen('settingsScreen')}else if(a==='back')this.showMain()});
 document.getElementById('characterContinue').onclick=()=>{if(this.selectedCharacter){this.renderMaps();this.showScreen('mapScreen')}};document.getElementById('startGameButton').onclick=()=>{if(this.selectedCharacter&&this.selectedMap)this.game.start(this.selectedCharacter,this.selectedMap)};
 document.querySelectorAll('[data-pause]').forEach(b=>b.onclick=()=>{const a=b.dataset.pause;if(a==='resume')this.game.togglePause();if(a==='restart'){this.hidePause();this.game.restart()}if(a==='quit'){this.hidePause();this.game.quit()}if(a==='settings'){this.flashMessage('Configurações podem ser alteradas no menu principal.')}});document.getElementById('retryButton').onclick=()=>{this.hideEnd();this.game.restart()};document.getElementById('menuButton').onclick=()=>{this.hideEnd();this.game.quit()};}
 renderCharacters(){const box=document.getElementById('characterCards');box.innerHTML='';for(const[id,c]of Object.entries(CHARACTERS)){const unlocked=this.save.data.unlocked.includes(id);const d=document.createElement('div');d.className='game-card'+(this.selectedCharacter===id?' selected':'')+(!unlocked?' locked':'');d.innerHTML=`<div class="portrait">${c.icon}</div><h3>${c.name}</h3><span class="tag">${WEAPONS[c.startWeapon].name}</span><p>${c.description}</p><p class="small"><b>Passiva:</b> ${c.passive}</p><div class="statline"><span>HP</span><b>${c.base.hp}</b></div><div class="statline"><span>Velocidade</span><b>${c.base.speed}</b></div>${unlocked?'':'<p class="small">🔒 '+c.unlock+'</p>'}`;if(unlocked)d.onclick=()=>{this.selectedCharacter=id;this.renderCharacters();document.getElementById('characterContinue').disabled=false};box.appendChild(d)}document.getElementById('characterContinue').disabled=!this.selectedCharacter}
 renderMaps(){const box=document.getElementById('mapCards');box.innerHTML='';for(const[id,m]of Object.entries(MAPS)){const unlocked=m.unlock===true||(m.unlock==='victory'&&this.save.data.records.wins>0);const d=document.createElement('div');d.className='game-card'+(this.selectedMap===id?' selected':'')+(!unlocked?' locked':'');d.innerHTML=`<div class="portrait">${m.icon}</div><h3>${m.name}</h3><p>${m.description}</p>${unlocked?'':'<p class="small">🔒 Vença uma partida</p>'}`;if(unlocked)d.onclick=()=>{this.selectedMap=id;this.renderMaps();document.getElementById('startGameButton').disabled=false};box.appendChild(d)}document.getElementById('startGameButton').disabled=!this.selectedMap}
 renderMeta(){document.getElementById('metaCoins').textContent=this.save.data.coins;const box=document.getElementById('metaCards');box.innerHTML='';for(const[id,m]of Object.entries(META_UPGRADES)){const lv=this.save.data.meta[id]||0,cost=Math.floor(m.baseCost*Math.pow(1.65,lv));const d=document.createElement('div');d.className='upgrade-card';d.innerHTML=`<h3>${m.name} ${lv}/${m.max}</h3><p>${m.desc}</p><button ${lv>=m.max||this.save.data.coins<cost?'disabled':''}>${lv>=m.max?'MÁXIMO':`Comprar • ${cost} ◈`}</button>`;d.querySelector('button').onclick=()=>{if(lv>=m.max||this.save.data.coins<cost)return;this.save.data.coins-=cost;this.save.data.meta[id]=lv+1;this.save.write();this.renderMeta()};box.appendChild(d)}}
 renderGrimoire(){const box=document.getElementById('grimoireList');box.innerHTML='';for(const e of EVOLUTIONS){const known=this.save.data.evolutions.includes(e.id);const d=document.createElement('div');d.className='grimoire-row';d.innerHTML=known?`<b>${e.name}</b><div class="small">${e.desc}</div>`:`<b>???</b><div class="small">Combinação ainda não descoberta</div>`;box.appendChild(d)}}
 renderSettings(){const s=this.save.data.settings,box=document.getElementById('settingsForm');box.innerHTML='';const ranges=[['master','Volume geral'],['music','Música'],['sfx','Efeitos sonoros']];for(const[k,label]of ranges){const d=document.createElement('label');d.className='setting';d.innerHTML=`<span>${label}</span><input type="range" min="0" max="1" step="0.05" value="${s[k]}">`;d.querySelector('input').oninput=e=>{s[k]=+e.target.value;this.save.write()};box.appendChild(d)}const toggles=[['damageNumbers','Números de dano'],['shake','Screen shake'],['performance','Modo performance'],['debug','Debug / FPS']];for(const[k,label]of toggles){const d=document.createElement('label');d.className='setting';d.innerHTML=`<span>${label}</span><input type="checkbox" ${s[k]?'checked':''}>`;d.querySelector('input').onchange=e=>{s[k]=e.target.checked;this.save.write()};box.appendChild(d)}const p=document.createElement('label');p.className='setting';p.innerHTML=`<span>Partículas</span><input type="range" min="0" max="3" step="1" value="${s.particles}">`;p.querySelector('input').oninput=e=>{s.particles=+e.target.value;this.save.write()};box.appendChild(p)}
 updateHUD(g){const p=g.player;document.getElementById('hpText').textContent=`${Math.ceil(p.hp)}/${Math.ceil(p.maxHp)}`;document.getElementById('hpFill').style.width=`${100*p.hp/p.maxHp}%`;document.getElementById('levelText').textContent=p.level;document.getElementById('xpFill').style.width=`${100*p.xpNow/p.xpNeed}%`;document.getElementById('killsText').textContent=p.kills;document.getElementById('runCoinsText').textContent=p.coins;document.getElementById('timer').textContent=this.fmt(g.time);const boss=g.enemies.find(e=>e.boss&&!e.dead);const bh=document.getElementById('bossHud');if(boss){bh.classList.remove('hidden');document.getElementById('bossName').textContent=boss.name;document.getElementById('bossFill').style.width=`${100*boss.hp/boss.maxHp}%`}else bh.classList.add('hidden');const dbg=document.getElementById('debugHud');if(this.save.data.settings.debug){dbg.classList.remove('hidden');dbg.textContent=`FPS ~ ${Math.round(1/Math.max(.001,(performance.now()-g.last)/1000))}\nInimigos ${g.enemies.length}\nProjéteis ${g.projectiles.length}\nPartículas ${g.particles.length}\nPos ${Math.round(p.x)}, ${Math.round(p.y)}\nTempo ${g.time.toFixed(1)}s`}else dbg.classList.add('hidden')}
 refreshWeaponBar(p){const box=document.getElementById('weaponBar');box.innerHTML='';for(const[id,lv]of Object.entries(p.weapons)){const w=WEAPONS[id];if(!w)continue;const d=document.createElement('div');d.className='weapon-slot';d.title=w.name;d.innerHTML=`<b>${w.icon}</b><span>Nv.${lv}</span>`;box.appendChild(d)}for(let i=Object.keys(p.weapons).length;i<6;i++){const d=document.createElement('div');d.className='weapon-slot';d.innerHTML='<span>—</span>';box.appendChild(d)}}
 showLevelUp(choices,onPick){const modal=document.getElementById('levelUpModal'),box=document.getElementById('levelChoices');box.innerHTML='';for(const c of choices){const d=document.createElement('div');d.className=`choice-card rarity-${c.rarity}`;d.innerHTML=`<span class="tag">${c.rarity.toUpperCase()}</span><h3>${c.icon} ${c.name}</h3><p>${c.desc}</p>`;d.onclick=()=>{modal.classList.add('hidden');onPick(c)};box.appendChild(d)}modal.classList.remove('hidden')}
 showPause(show){document.getElementById('pauseModal').classList.toggle('hidden',!show)}hidePause(){document.getElementById('pauseModal').classList.add('hidden')}
 showChest(c,done){const m=document.getElementById('chestModal');document.getElementById('chestReward').innerHTML=c?`<h3>${c.icon} ${c.name}</h3><p>${c.desc}</p>`:'<p>Moedas ancestrais.</p>';m.classList.remove('hidden');document.getElementById('chestContinue').onclick=()=>{m.classList.add('hidden');done()}}
 showEnd(g,victory){const p=g.player,m=document.getElementById('endModal');document.getElementById('endTitle').textContent=victory?'VITÓRIA':'VOCÊ CAIU';const best=Object.entries(g.weaponDamage).sort((a,b)=>b[1]-a[1])[0];document.getElementById('endStats').innerHTML=`<div><span>Tempo</span><b>${this.fmt(g.time)}</b></div><div><span>Nível</span><b>${p.level}</b></div><div><span>Inimigos derrotados</span><b>${p.kills}</b></div><div><span>Dano causado</span><b>${Math.round(p.damageDone)}</b></div><div><span>Moedas</span><b>${p.coins}</b></div><div><span>Chefe final</span><b>${victory?'Derrotado':'Não derrotado'}</b></div><div><span>Maior fonte de dano</span><b>${best?best[0]:'—'}</b></div>`;m.classList.remove('hidden')}
 hideEnd(){document.getElementById('endModal').classList.add('hidden')}
 setBoss(){}
 flashMessage(text){let d=document.createElement('div');d.textContent=text;d.style.cssText='position:fixed;z-index:80;top:18%;left:50%;transform:translateX(-50%);padding:14px 20px;background:#0b1d19e8;border:1px solid #d6ae52;border-radius:12px;font-weight:900;';document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
 fmt(t){const m=Math.floor(t/60),s=Math.floor(t%60);return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
}
