function hashString(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
function pointSegmentDistance(px,py,ax,ay,bx,by){const abx=bx-ax,aby=by-ay,apx=px-ax,apy=py-ay,den=abx*abx+aby*aby||1;const t=Math.max(0,Math.min(1,(apx*abx+apy*aby)/den));return Math.hypot(px-(ax+abx*t),py-(ay+aby*t));}

const BIOMES={
  ruins:{detail:'#2d584c',light:'#67b89c',dark:'#071714',path:'#6d6d59',pathEdge:'#2a423b',types:['rune','rubble','crystal','crack','moss'],obstacles:['pillar','rock','ruin'],poi:['brokenTower','arcaneShrine','ritualCircle','collapsedHall'],water:'arcaneBasin'},
  forest:{detail:'#315b39',light:'#65a86f',dark:'#07130c',path:'#66563d',pathEdge:'#243927',types:['grass','shrub','root','mushroom','leaf'],obstacles:['tree','rock'],poi:['ancientGrove','cemetery','witchHut','stoneShrine'],water:'pond'},
  ash:{detail:'#6b3d2d',light:'#b85f3d',dark:'#160d0a',path:'#835a3f',pathEdge:'#43271d',types:['bone','crack','drygrass','rubble','ash'],obstacles:['rock','ruin'],poi:['boneField','buriedRuins','abandonedCamp','lavaShrine'],water:'lavaPool'},
  frost:{detail:'#44727b',light:'#8ac8d6',dark:'#091619',path:'#86989a',pathEdge:'#344c51',types:['snow','icecrack','crystal','stone','frostgrass'],obstacles:['iceRock','pillar'],poi:['iceSanctum','frozenGrove','brokenWatch','crystalGarden'],water:'frozenLake'},
  city:{detail:'#565d5b',light:'#8c9692',dark:'#151817',path:'#77736d',pathEdge:'#3a3d3b',types:['rubble','mark','bone','rune','debris'],obstacles:['ruin','pillar','rock'],poi:['centralPlaza','collapsedGate','ruinedMarket','watchTower'],water:'puddle'},
  void:{detail:'#5c3b76',light:'#aa6bd2',dark:'#0d0714',path:'#674b79',pathEdge:'#2d1c3c',types:['voidcrack','rune','crystal','shard','spark'],obstacles:['voidCrystal','rock','pillar'],poi:['riftNexus','obeliskField','silentShrine','brokenRing'],water:'voidPool'}
};

function obstacleProfile(type,r){
  if(type==='tree')return{hitbox:r*.36,visual:r*1.28};
  if(type==='pillar')return{hitbox:r*.57,visual:r*1.18};
  if(type==='ruin')return{hitbox:r*.72,visual:r*1.28};
  if(type==='voidCrystal')return{hitbox:r*.48,visual:r*1.38};
  return{hitbox:r*.66,visual:r*1.14};
}

export class WorldMap{
  constructor(mapId,map,width,height){this.mapId=mapId;this.map=map;this.width=width;this.height=height;this.palette=BIOMES[mapId]||BIOMES.ruins;this.decorations=[];this.obstacles=[];this.paths=[];this.waterBodies=[];this.pois=[];this.zones=[];this.seed=hashString(`arcane-horder:${mapId}:2.4.0`);this.generate();}

  generate(){const random=rng(this.seed);this.generateZones(random);this.generatePois(random);this.generatePaths(random);this.generateWater(random);this.generateDecorations(random);this.generateObstacles(random);this.addPoiStructures(random);}

  generateZones(random){for(let i=0;i<8;i++){this.zones.push({x:420+random()*(this.width-840),y:420+random()*(this.height-840),rx:260+random()*520,ry:180+random()*380,rot:random()*Math.PI,color:i%2?this.palette.detail:this.palette.light});}}

  generatePois(random){const cx=this.width/2,cy=this.height/2,count=6;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2+(random()-.5)*.5;const d=850+random()*1550;const x=Math.max(260,Math.min(this.width-260,cx+Math.cos(a)*d));const y=Math.max(260,Math.min(this.height-260,cy+Math.sin(a)*d));this.pois.push({type:this.palette.poi[i%this.palette.poi.length],x,y,r:95+random()*55,rot:random()*Math.PI*2});}}

  generatePaths(random){const center={x:this.width/2,y:this.height/2};for(const poi of this.pois){const points=[center];const segments=5;for(let i=1;i<segments;i++){const t=i/segments;const bx=center.x+(poi.x-center.x)*t,by=center.y+(poi.y-center.y)*t;const a=Math.atan2(poi.y-center.y,poi.x-center.x)+Math.PI/2;const jitter=(random()-.5)*150*(Math.sin(Math.PI*t));points.push({x:bx+Math.cos(a)*jitter,y:by+Math.sin(a)*jitter});}points.push({x:poi.x,y:poi.y});this.paths.push({points,width:55+random()*30});}
    for(let i=0;i<this.pois.length;i+=2){const a=this.pois[i],b=this.pois[(i+1)%this.pois.length];this.paths.push({points:[{x:a.x,y:a.y},{x:(a.x+b.x)/2+(random()-.5)*100,y:(a.y+b.y)/2+(random()-.5)*100},{x:b.x,y:b.y}],width:42});}
  }

  generateWater(random){const count=this.mapId==='forest'?4:this.mapId==='frost'?3:this.mapId==='ash'?2:this.mapId==='void'?3:this.mapId==='ruins'?2:this.mapId==='city'?2:1;for(let i=0;i<count;i++){let x,y,tries=0;do{x=320+random()*(this.width-640);y=320+random()*(this.height-640);tries++;}while((this.isNearPath(x,y,170)||Math.hypot(x-this.width/2,y-this.height/2)<520)&&tries<30);const rx=80+random()*110,ry=55+random()*80;const type=this.palette.water;const blocked=['pond','lavaPool','voidPool','arcaneBasin'].includes(type);const miniColor=type==='lavaPool'?'#c05b36':type==='voidPool'?'#6c48a0':type==='frozenLake'?'#80c7d4':type==='puddle'?'#54757b':'#4d8790';this.waterBodies.push({type,x,y,rx,ry,rot:random()*Math.PI,blocked,miniColor});}}

  generateDecorations(random){const clusters=30;for(let c=0;c<clusters;c++){const anchor=this.pois[c%this.pois.length]||{x:200+random()*(this.width-400),y:200+random()*(this.height-400)};const usePoi=random()<.55;const cx=usePoi?anchor.x+(random()-.5)*260:180+random()*(this.width-360),cy=usePoi?anchor.y+(random()-.5)*260:180+random()*(this.height-360);const count=8+Math.floor(random()*11);for(let i=0;i<count;i++){const a=random()*Math.PI*2,d=Math.sqrt(random())*(80+random()*190),x=cx+Math.cos(a)*d,y=cy+Math.sin(a)*d;if(x<60||y<60||x>this.width-60||y>this.height-60)continue;if(Math.hypot(x-this.width/2,y-this.height/2)<220)continue;const type=this.palette.types[Math.floor(random()*this.palette.types.length)];this.decorations.push({type,x,y,size:5+random()*17,rot:random()*Math.PI*2,variant:Math.floor(random()*5)});}}}

  generateObstacles(random){const target=62;let attempts=0;while(this.obstacles.length<target&&attempts<target*35){attempts++;const x=130+random()*(this.width-260),y=130+random()*(this.height-260);if(Math.hypot(x-this.width/2,y-this.height/2)<360)continue;if(this.isNearPath(x,y,95))continue;if(this.waterBodies.some(w=>Math.hypot(w.x-x,w.y-y)<Math.max(w.rx,w.ry)+90))continue;const base=22+random()*35;if(this.obstacles.some(o=>Math.hypot(o.x-x,o.y-y)<o.visual+base+36))continue;const type=this.palette.obstacles[Math.floor(random()*this.palette.obstacles.length)],p=obstacleProfile(type,base);this.obstacles.push({type,x,y,hitbox:p.hitbox,visual:p.visual,rot:random()*Math.PI*2,variant:Math.floor(random()*5)});}}

  addPoiStructures(random){for(const poi of this.pois){if(/Tower|tower|Hall|Gate|Market|Plaza|Ruins|Sanctum|Shrine|Ring|Nexus/.test(poi.type)){const count=poi.type.includes('Plaza')?4:3;for(let i=0;i<count;i++){const a=poi.rot+i*Math.PI*2/count,d=poi.r*.7;const type=this.mapId==='forest'?'rock':this.mapId==='void'?'voidCrystal':i%2?'pillar':'ruin';const base=26+random()*16,p=obstacleProfile(type,base);const x=poi.x+Math.cos(a)*d,y=poi.y+Math.sin(a)*d;if(!this.obstacles.some(o=>Math.hypot(o.x-x,o.y-y)<55)&&!this.isNearPath(x,y,40))this.obstacles.push({type,x,y,hitbox:p.hitbox,visual:p.visual,rot:a,variant:i});}}}}

  isNearPath(x,y,margin=70){for(const path of this.paths){for(let i=1;i<path.points.length;i++){const a=path.points[i-1],b=path.points[i];if(pointSegmentDistance(x,y,a.x,a.y,b.x,b.y)<margin+(path.width||50)*.5)return true;}}return false;}

  waterCollision(x,y,r){for(const w of this.waterBodies){if(!w.blocked)continue;const dx=(x-w.x)/(w.rx+r),dy=(y-w.y)/(w.ry+r);if(dx*dx+dy*dy<1)return w;}return null;}
  collidesCircle(x,y,r){for(const o of this.obstacles)if(Math.hypot(x-o.x,y-o.y)<r+o.hitbox)return o;return this.waterCollision(x,y,r);}
  resolveMovement(player,nx,ny){const r=player.hitboxRadius??player.r;let x=nx,y=player.y;if(this.collidesCircle(x,y,r))x=player.x;y=ny;if(this.collidesCircle(x,y,r))y=player.y;return{x,y};}
  findNearestFree(x,y,r=26){x=Math.max(r+12,Math.min(this.width-r-12,x));y=Math.max(r+12,Math.min(this.height-r-12,y));if(!this.collidesCircle(x,y,r))return{x,y};for(let ring=1;ring<=12;ring++)for(let i=0;i<16;i++){const a=i*Math.PI*2/16,d=ring*34,nx=Math.max(r+12,Math.min(this.width-r-12,x+Math.cos(a)*d)),ny=Math.max(r+12,Math.min(this.height-r-12,y+Math.sin(a)*d));if(!this.collidesCircle(nx,ny,r))return{x:nx,y:ny};}return{x,y};}

  draw(ctx,game){ctx.fillStyle=this.map.ground;ctx.fillRect(0,0,innerWidth,innerHeight);this.drawZones(ctx,game);this.drawPaths(ctx,game);this.drawWater(ctx,game);this.drawGroundTexture(ctx,game);this.drawPois(ctx,game);this.drawDecorations(ctx,game);this.drawObstacleBases(ctx,game);this.drawBounds(ctx,game);}

  drawZones(ctx,game){for(const z of this.zones){if(!game.camera.visible(z.x,z.y,Math.max(z.rx,z.ry)))continue;const s=game.camera.worldToScreen(z.x,z.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(z.rot);ctx.globalAlpha=.055;ctx.fillStyle=z.color;ctx.beginPath();ctx.ellipse(0,0,z.rx,z.ry,0,0,Math.PI*2);ctx.fill();ctx.restore();}}

  drawPaths(ctx,game){const cam=game.camera;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';for(const path of this.paths){let visible=false;for(const pt of path.points){if(game.camera.visible(pt.x,pt.y,120)){visible=true;break;}}if(!visible)continue;ctx.strokeStyle=this.palette.pathEdge;ctx.lineWidth=(path.width||55)+14;ctx.globalAlpha=.28;ctx.beginPath();path.points.forEach((pt,i)=>{const s=cam.worldToScreen(pt.x,pt.y);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y);});ctx.stroke();ctx.strokeStyle=this.palette.path;ctx.lineWidth=path.width||55;ctx.globalAlpha=.35;ctx.stroke();ctx.strokeStyle=this.palette.light;ctx.lineWidth=2;ctx.globalAlpha=.10;ctx.stroke();}ctx.restore();}

  drawWater(ctx,game){for(const w of this.waterBodies){if(!game.camera.visible(w.x,w.y,Math.max(w.rx,w.ry)+20))continue;const s=game.camera.worldToScreen(w.x,w.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(w.rot);ctx.globalAlpha=.85;const fill=w.type==='lavaPool'?'#873623':w.type==='voidPool'?'#4c286c':w.type==='frozenLake'?'#5c9dac':w.type==='puddle'?'#344e53':'#315f67';ctx.fillStyle=fill;ctx.strokeStyle=w.type==='lavaPool'?'#d96c3d':w.type==='voidPool'?'#b46cff':w.type==='frozenLake'?'#b9edf3':'#6fb2b8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-w.rx*.95,-w.ry*.05);ctx.bezierCurveTo(-w.rx*.8,-w.ry*.9,-w.rx*.15,-w.ry*1.05,w.rx*.25,-w.ry*.82);ctx.bezierCurveTo(w.rx*.85,-w.ry*.65,w.rx*1.05,-w.ry*.1,w.rx*.88,w.ry*.35);ctx.bezierCurveTo(w.rx*.55,w.ry*.92,-w.rx*.2,w.ry*1.02,-w.rx*.75,w.ry*.63);ctx.bezierCurveTo(-w.rx*1.03,w.ry*.4,-w.rx*1.07,w.ry*.12,-w.rx*.95,-w.ry*.05);ctx.closePath();ctx.fill();ctx.stroke();ctx.globalAlpha=.28;ctx.strokeStyle='#e9ffff';ctx.lineWidth=1.2;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse((i-1)*w.rx*.2,(i%2?1:-1)*w.ry*.18,w.rx*.22,w.ry*.06,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}}

  drawGroundTexture(ctx,game){const cam=game.camera,step=82,p=this.palette,sx=Math.floor(cam.x/step)*step,sy=Math.floor(cam.y/step)*step;ctx.save();for(let x=sx;x<cam.x+cam.w+step;x+=step)for(let y=sy;y<cam.y+cam.h+step;y+=step){const h=Math.abs(((x*73856093)^(y*19349663)^this.seed)>>>0),px=x-cam.x,py=y-cam.y;ctx.globalAlpha=.075+(h%5)*.012;const kind=h%6;if(this.mapId==='forest'&&(kind<3)){ctx.strokeStyle=p.light;ctx.lineWidth=1;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(px+(h%31)+i*3,py+(h%23)+7);ctx.lineTo(px+(h%31)+i*3-2,py+(h%23)-4-(h%5));ctx.stroke();}}else if(this.mapId==='frost'&&kind<3){ctx.fillStyle='#cce4e7';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(px+(h%34)+i*4,py+(h%26)+(i%2)*3,1.2,0,Math.PI*2);ctx.fill();}}else if(this.mapId==='ash'&&kind<3){ctx.strokeStyle='#a85c3d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px+8,py+18);ctx.lineTo(px+20,py+12);ctx.lineTo(px+28,py+20);ctx.stroke();}else{ctx.fillStyle=(h&1)?p.detail:p.light;ctx.beginPath();ctx.ellipse(px+(h%31),py+(h%23),7+(h%13),2+(h%5),(h%314)/100,0,Math.PI*2);ctx.fill();}}ctx.restore();}

  drawPois(ctx,game){for(const poi of this.pois){if(!game.camera.visible(poi.x,poi.y,poi.r+80))continue;const s=game.camera.worldToScreen(poi.x,poi.y),r=poi.r;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(poi.rot);ctx.globalAlpha=.82;if(/cemetery|boneField/.test(poi.type)){ctx.strokeStyle='#bcb59c';ctx.lineWidth=2;for(let i=0;i<6;i++){const a=i*Math.PI*2/6,rr=r*.55,x=Math.cos(a)*rr,y=Math.sin(a)*rr;ctx.beginPath();ctx.moveTo(x,y-6);ctx.lineTo(x,y+8);ctx.moveTo(x-4,y-2);ctx.lineTo(x+4,y-2);ctx.stroke();}}else if(/Grove|grove|Garden/.test(poi.type)){ctx.strokeStyle=this.palette.light;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,r*.62,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(a)*r*.42,Math.sin(a)*r*.42);ctx.lineTo(Math.cos(a)*r*.68,Math.sin(a)*r*.68);ctx.stroke();}}else if(/Plaza|Circle|Shrine|Nexus|Ring|Sanctum/.test(poi.type)){ctx.strokeStyle=this.palette.light;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,r*.55,0,Math.PI*2);ctx.stroke();ctx.lineWidth=1;for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.beginPath();ctx.moveTo(Math.cos(a)*r*.25,Math.sin(a)*r*.25);ctx.lineTo(Math.cos(a)*r*.52,Math.sin(a)*r*.52);ctx.stroke();}}else{ctx.fillStyle='rgba(110,105,95,.42)';ctx.fillRect(-r*.55,-r*.25,r*1.1,r*.5);ctx.strokeStyle=this.palette.light;ctx.strokeRect(-r*.55,-r*.25,r*1.1,r*.5);}ctx.restore();}}

  drawDecorations(ctx,game){const q=Number(game.save.data.settings.quality??2),stride=q<=0?4:q===1?2:1;for(let i=0;i<this.decorations.length;i+=stride){const d=this.decorations[i];if(!game.camera.visible(d.x,d.y,d.size+20))continue;this.drawDecoration(ctx,game,d);}}
  drawDecoration(ctx,game,d){const s=game.camera.worldToScreen(d.x,d.y),p=this.palette;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(d.rot);ctx.globalAlpha=.66;switch(d.type){case'grass':case'drygrass':case'frostgrass':ctx.strokeStyle=d.type==='drygrass'?'#9c7750':d.type==='frostgrass'?'#9ac6c7':p.light;ctx.lineWidth=1.4;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*2,3);ctx.quadraticCurveTo(i*3,-d.size*.35,i*1.2,-d.size);ctx.stroke();}break;case'shrub':ctx.fillStyle=p.detail;for(let i=0;i<5;i++){const a=i*Math.PI*2/5;ctx.beginPath();ctx.ellipse(Math.cos(a)*d.size*.35,Math.sin(a)*d.size*.2,d.size*.35,d.size*.22,a,0,Math.PI*2);ctx.fill();}break;case'root':ctx.strokeStyle='#6b4d35';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(d.size*.3,-d.size*.3,d.size*(.7+i*.18),(-1+i)*4);ctx.stroke();}break;case'mushroom':ctx.fillStyle='#c9d9b2';ctx.fillRect(-2,0,4,d.size*.55);ctx.fillStyle='#8b6bb8';ctx.beginPath();ctx.arc(0,0,d.size*.35,Math.PI,Math.PI*2);ctx.fill();break;case'leaf':ctx.fillStyle=p.light;ctx.beginPath();ctx.ellipse(0,0,d.size*.6,d.size*.25,0,0,Math.PI*2);ctx.fill();break;case'rune':ctx.strokeStyle=p.light;ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(0,0,d.size*.5,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-d.size*.35,0);ctx.lineTo(d.size*.35,0);ctx.moveTo(0,-d.size*.35);ctx.lineTo(0,d.size*.35);ctx.stroke();break;case'crystal':case'shard':ctx.fillStyle=p.light;ctx.beginPath();ctx.moveTo(0,-d.size);ctx.lineTo(d.size*.45,d.size*.25);ctx.lineTo(0,d.size*.55);ctx.lineTo(-d.size*.4,d.size*.25);ctx.closePath();ctx.fill();break;case'bone':ctx.strokeStyle='#d8d0b4';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-d.size*.5,0);ctx.lineTo(d.size*.5,0);ctx.stroke();break;case'crack':case'icecrack':case'voidcrack':ctx.strokeStyle=d.type==='icecrack'?'#92d7e8':d.type==='voidcrack'?'#b05cff':p.detail;ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(-d.size,0);ctx.lineTo(-d.size*.35,-3);ctx.lineTo(0,4);ctx.lineTo(d.size*.4,-5);ctx.lineTo(d.size,2);ctx.stroke();break;case'rubble':case'stone':case'debris':ctx.fillStyle=p.detail;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(-d.size*.4+i*5,4);ctx.lineTo(-d.size*.25+i*5,-5);ctx.lineTo(d.size*.1+i*4,-3);ctx.lineTo(d.size*.25+i*4,5);ctx.closePath();ctx.fill();}break;case'snow':case'ash':case'spark':ctx.fillStyle=d.type==='snow'?'#dceff2':d.type==='spark'?'#c985ff':'#a98570';for(let i=0;i<4;i++){ctx.beginPath();ctx.arc((i-2)*3,(i%2)*2,1.4,0,Math.PI*2);ctx.fill();}break;case'mark':ctx.strokeStyle='#836e66';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-d.size*.6,-d.size*.4);ctx.lineTo(d.size*.6,d.size*.4);ctx.moveTo(d.size*.55,-d.size*.5);ctx.lineTo(-d.size*.5,d.size*.45);ctx.stroke();break;case'moss':ctx.fillStyle='#4e7f63';ctx.beginPath();ctx.ellipse(0,0,d.size,d.size*.3,0,0,Math.PI*2);ctx.fill();break;}ctx.restore();}

  drawObstacleBases(ctx,game){for(const o of this.obstacles){if(!game.camera.visible(o.x,o.y,o.visual+30))continue;this.drawObstacleBase(ctx,game,o);}}
  drawObstacleBase(ctx,game,o){const s=game.camera.worldToScreen(o.x,o.y),p=this.palette,r=o.visual;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(o.rot);ctx.globalAlpha=.28;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(5,r*.48,r*.72,r*.26,.15,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(o.type==='tree'){ctx.fillStyle='#4b3628';ctx.fillRect(-r*.12,-r*.12,r*.24,r*.95);ctx.strokeStyle='#684735';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-r*.05);ctx.lineTo(-r*.32,-r*.45);ctx.moveTo(0,-r*.18);ctx.lineTo(r*.34,-r*.52);ctx.stroke();ctx.fillStyle='#244a2f';ctx.beginPath();ctx.ellipse(0,-r*.48,r*.44,r*.24,0,0,Math.PI*2);ctx.fill();}else if(o.type==='rock'||o.type==='iceRock'){ctx.fillStyle=o.type==='iceRock'?'#6f9ba5':p.detail;ctx.strokeStyle=p.dark;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-r*.7,r*.35);ctx.lineTo(-r*.55,-r*.25);ctx.lineTo(-r*.1,-r*.7);ctx.lineTo(r*.55,-r*.45);ctx.lineTo(r*.72,r*.18);ctx.lineTo(r*.35,r*.58);ctx.lineTo(-r*.35,r*.62);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=p.light;ctx.beginPath();ctx.moveTo(-r*.15,-r*.55);ctx.lineTo(r*.35,-r*.34);ctx.stroke();}else if(o.type==='pillar'||o.type==='ruin'){ctx.fillStyle='#756f66';ctx.fillRect(-r*.35,-r*.8,r*.7,r*1.45);ctx.fillStyle='#938c80';ctx.fillRect(-r*.48,-r*.83,r*.96,r*.18);ctx.fillStyle='#514c46';ctx.fillRect(-r*.42,r*.5,r*.84,r*.16);if(o.type==='ruin'){ctx.fillStyle='#5f5a54';ctx.fillRect(r*.1,-r*.2,r*.75,r*.28);}}else if(o.type==='voidCrystal'){ctx.fillStyle='#8e4fba';ctx.strokeStyle='#d184ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-r);ctx.lineTo(r*.45,r*.35);ctx.lineTo(0,r*.7);ctx.lineTo(-r*.45,r*.35);ctx.closePath();ctx.fill();ctx.stroke();}ctx.restore();}

  drawForeground(ctx,game){for(const o of this.obstacles){if(o.type!=='tree'&&o.type!=='ruin')continue;if(!game.camera.visible(o.x,o.y,o.visual+50))continue;const dist=Math.hypot(game.player.x-o.x,game.player.y-o.y),alpha=dist<85?.42:.88,s=game.camera.worldToScreen(o.x,o.y),r=o.visual;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(o.rot);ctx.globalAlpha=alpha;if(o.type==='tree'){ctx.fillStyle=this.palette.detail;const blobs=[[-.32,-.72,.54],[.30,-.70,.50],[0,-.96,.58],[-.08,-.50,.48]];for(const[bX,bY,br]of blobs){ctx.beginPath();ctx.ellipse(bX*r,bY*r,br*r*.78,br*r*.50,0,0,Math.PI*2);ctx.fill();}ctx.strokeStyle=this.palette.light;ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,-r*.78,r*.3,0,Math.PI*2);ctx.stroke();}else{ctx.fillStyle='#817a70';ctx.fillRect(-r*.48,-r*.9,r*.96,r*.16);ctx.fillStyle='#5b5650';ctx.fillRect(r*.08,-r*.32,r*.82,r*.18);}ctx.restore();}}

  drawBounds(ctx,game){const cam=game.camera,margin=78,p=this.palette;ctx.save();ctx.globalAlpha=.76;ctx.fillStyle=p.dark;if(cam.x<margin)ctx.fillRect(-cam.x,0,margin,innerHeight);if(cam.y<margin)ctx.fillRect(0,-cam.y,innerWidth,margin);if(cam.x+cam.w>this.width-margin)ctx.fillRect(this.width-margin-cam.x,0,margin,innerHeight);if(cam.y+cam.h>this.height-margin)ctx.fillRect(0,this.height-margin-cam.y,innerWidth,margin);ctx.globalAlpha=1;ctx.strokeStyle=p.light;ctx.lineWidth=4;ctx.setLineDash([14,8]);ctx.strokeRect(-cam.x,-cam.y,this.width,this.height);ctx.setLineDash([]);ctx.restore();}

  drawDebug(ctx,game){ctx.save();ctx.strokeStyle='#62f3ff';ctx.lineWidth=1.5;for(const o of this.obstacles){if(!game.camera.visible(o.x,o.y,o.hitbox+4))continue;const s=game.camera.worldToScreen(o.x,o.y);ctx.beginPath();ctx.arc(s.x,s.y,o.hitbox,0,Math.PI*2);ctx.stroke();}ctx.strokeStyle='#ff8c5f';for(const w of this.waterBodies){if(!w.blocked||!game.camera.visible(w.x,w.y,Math.max(w.rx,w.ry)))continue;const s=game.camera.worldToScreen(w.x,w.y);ctx.beginPath();ctx.ellipse(s.x,s.y,w.rx,w.ry,w.rot||0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
}
